[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["macros"] }
utoipa = { version = "5.2.0" }